### ISSUE TITLE
[Feature Request] Havoc Store extension tab support

### ISSUE THREAD

**Issue by p4p1** [RalfHacker/Kerbeus-BOF#2]
Hey found this module thought it was pretty cool, could it be integrated with the Havoc Extensions tab:
![image](https://github.com/RalfHacker/Kerbeus-BOF/assets/19672114/2fbc6581-315b-4761-b9fe-773990e9f384)

To be implemented inside of that tab you would need to open a pull request on:
[https://p4p1.github.io/havoc-store/](https://p4p1.github.io/havoc-store/)

**Comment by RalfHacker** [comment]
Good idea) but this repo doesn't contain bin files
